name: Lingui extract - Gaming
on:
  pull_request:
    branches:
      - "dev"
    paths:
    - "packages/gaming-ui/**/*"
jobs:
  # extract any new translatable string
  # and commit if there are new ones
  extract:
    name: lingui-extract
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.LINGUI_GH_ACTION_COMMIT_KEY }}

    - name: set user
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    # use node module caching
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: install packages
      run: yarn install --immutable

    - name: lingui-extract
      run: |
        (cd packages/gaming-ui && yarn extract --clean)
        git add packages/gaming-ui/src/locales/*
        if git commit -m "lingui extract"; then git push; else echo 'exiting successfully without commit'; fi
