name: Cypress tests - Storage
on: 
  pull_request:
    paths:
    - "packages/storage-ui/**/*"
    - "packages/common-components/**/*"
    - "packages/common-theme/**/*"
    - package.json
    - .eslintrc.json
    - tsconfig.json
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
            **/build
          key: ${{ runner.os }}-node_modules-build-storage-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GH_PKG_AUTH_TOKEN }}
          REACT_APP_API_URL: ${{ secrets.GH_REACT_APP_API_URL }}
          REACT_APP_BLOCKNATIVE_ID: ${{ secrets.GH_REACT_APP_BLOCKNATIVE_ID }}
          REACT_APP_FILES_VERIFIER_NAME: ${{ secrets.GH_REACT_APP_FILES_VERIFIER_NAME }}
          REACT_APP_FILES_UUID_VERIFIER_NAME: 'chainsafe-uuid-testnet'
        with:
          start: yarn start:storage-ui
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://127.0.0.1:3000'
          # wait for max 2 minutes for the storage-ui to respond
          wait-on-timeout: 120
          # custom test command to run
          command: yarn test:ci:storage-ui
      # store the screenshots if the tests fail
      - name: Store screenshots 
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/storage-ui/cypress/screenshots
      # store the videos if the tests fail
      # - name: Store videos 
      #   uses: actions/upload-artifact@v1
      #   if: failure()
      #   with:
      #     name: cypress-videos
      #     path: packages/storage-ui/cypress/videos
